version: '3.8'

services:
  postgress:
    image: postgres:last
    container_name: postgres_docker
    restart: always
    environment:
      POSTGRES_USER: yeorijby
      POSTGRES_PASSWORD: yeori1010
      POSTGRES_DB: school
    ports:
      - '15432:5432'
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://myuser:mypassword@[YOUR_SERVER_IP]:5432/mydb
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver:local