version: '3.8'

services:
  postgress:
    image: postgres:last
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: yeorijby
      POSTGRES_PASSWORD: yeori1010
      POSTGRES_DB: school
    ports:
      - '5432:5432'
  postgress2:
    image: postgres:last
    container_name: postgres-shadow
    restart: always
    environment:
      POSTGRES_USER: yeorijby
      POSTGRES_PASSWORD: yeori1010
      POSTGRES_DB: school
    ports:
      - '5433:5433'
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://myuser:mypassword@[YOUR_SERVER_IP]:5432/mydb
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver:local